version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-_-_1z2wmy#a-e1zr-lnjn@y11s1z*%an5+=le!259#13ntsfc("
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
