# Generated by Django 5.0.6 on 2024-06-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_product_og_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='og_price',
        ),
    ]
