# Generated by Django 5.0.6 on 2024-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_comment_recommend_alter_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recommend',
            field=models.CharField(blank=True, choices=[('اصلا پیشنهاد نمیکنم', 'اصلا پیشنهاد نمیکنم'), ('حتما پیشنهاد میکنم', 'حتما پیشنهاد میکنم')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, choices=[('خیلی بد بو', 'خیلی بد بود'), ('خوب بود', 'خوب بود'), ('خیلی عالی بود', 'خیلی عالی بود')], max_length=100),
        ),
    ]
