# Generated by Django 5.0.6 on 2024-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_the_amount_of_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vat',
            field=models.BooleanField(default=False),
        ),
    ]
